import os
import re


class TreeView:
    """
    TreeView no longer builds a tree from Graph.

    Its only job is to display HTML generated by another plugin
    (Simple Visualizer), either from:
    - a raw HTML string
    - or a file path to an HTML file

    If neither exists, it shows a fallback placeholder.
    """

    def __init__(self, html_content=None, html_path=None):
        self.html_content = html_content
        self.html_path = html_path

    def render(self):
        # Priority 1: directly provided HTML content
        if self.html_content and str(self.html_content).strip():
            return self._extract_body_if_full_document(self.html_content)

        # Priority 2: load HTML from file
        if self.html_path and os.path.isfile(self.html_path):
            with open(self.html_path, "r", encoding="utf-8") as f:
                html = f.read()
            return self._extract_body_if_full_document(html)

        # Fallback while Simple Visualizer does not exist yet
        return self._fallback_placeholder()

    def _extract_body_if_full_document(self, html):
        """
        If the provided HTML is a full document, return only the body.
        If it is already a fragment, return it unchanged.
        """
        match = re.search(
            r"<body[^>]*>(.*?)</body>",
            html,
            flags=re.IGNORECASE | re.DOTALL
        )

        if match:
            return match.group(1).strip()

        return html

    def _fallback_placeholder(self):
        return """
        <div class="tree-view-placeholder">
            <p>No graph data available.</p>
        </div>
        """